config/routes.rb
FacebookImagesUpload::Application.routes.draw do
  resources :events do
    resources :photos
  end

  resources :services do
    get 'import_status' => "services#import_status", :as => :import_status, :defaults => { :format => 'js' }
    get 'invite/:uid' => 'services#invite', :as => :invite
    post 'invite/:uid' => 'services#create_invitation', :as => :create_invitation
  end
  
  match "/auth/:provider/callback" => "services#create"
  match "/chat/:provider/:uid" => 'services#chat', :as => :chat
  match "/import/:provider" => "services#import", :as => :import
  
  mount Resque::Server, :at => "/resque"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  serialize :metadata, Hash
  belongs_to :event
  belongs_to :service
  has_many :photos
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/provider.rb
class Provider < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  serialize :metadata, Hash
  belongs_to :user
  belongs_to :provider
end

app/models/service_provider.rb
class Provider < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :services
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.first
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = current_user.events.find(params[:id])
    @photos = @event.photos
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  protect_from_forgery :except => :create

  def create
      auth = request.env["omniauth.auth"]
      provider = Provider.find_by_name(auth["provider"])
      @service = current_user.services.find_by_provider_id_and_uid(provider.id, auth["uid"]) || 
          current_user.services.create(
            :provider_id => provider.id,
            :uid => auth['uid'],
            :oauth_token => auth['credentials']['token'],
            :oauth_token_secret => auth['credentials']['secret'])
      redirect_to import_path(:provider => provider.name)
  end

  def destroy
    @service = current_user.services.find(params[:id])
    provider = @service.provider
    @service.destroy if @service
    redirect_to event_path(current_user.events.first.id)
  end
  
  def import
    @provider = Provider.find_by_name(params[:provider])
    @service = current_user.services.find_by_provider_id(@provider.id)
    @uncategorized_event = current_user.events.first #TODO: find uncategorized

    unless @service.import_started_at
      @service.update_attribute :import_started_at, Time.now
      if @provider.name == 'facebook'
        Resque.enqueue(FacebookImporter, @service.id) 
        Resque.enqueue(FacebookFriendsUpdater, @service.id) 
      end
    end

    redirect_to @uncategorized_event
  end

  def import_status
    @service = current_user.services.find(params[:service_id])
    respond_to do |format|
      format.js
    end
  end

  def chat
    @provider = Provider.find_by_name(params[:provider])
    @service = Service.find_by_provider_id_and_uid(@provider.id, params[:uid])
    if @service
      render :text => "chat with user=#{@service.user.name}"
    else
      @service = current_user.services.find_by_provider_id(@provider.id)
      redirect_to service_invite_path(:service_id => @service.id, :uid => params[:uid], :name => params[:name])
    end
  end
  
  # GET /services/:service_id/invite/:uid
  def invite
    @service = current_user.services.find(params[:service_id])
    @invited_service = Service.find_by_provider_id_and_uid(@service.provider.id, params[:uid])
    
    if @invited_service
      redirect_to chat_path(:provider => @service.provider.name, :uid => params[:uid])
      return
    end
  end
  
  # POST /services/:service_id/invite/:uid
  def create_invitation
    puts "service_id = #{params[:service_id]}"
    @service = current_user.services.find(params[:service_id])
    @invited_service = Service.find_by_provider_id_and_uid(@service.provider.id, params[:uid])
    
    if @invited_service
      redirect_to chat_path(:provider => @service.provider.name, :uid => params[:uid])
      return
    end
    
    if @service
      api = Koala::Facebook::API.new(@service.oauth_token)
      # TODO: change link
      api.put_wall_post(params[:message], {:name => "Example", :link => "http://www.example.com"}, params[:uid])
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/events/show.html.erb
<%= render :partial => 'services/import_statuses' %>

<%= render :partial => 'services/list' %>

<h1><%= @event.name %></h1>
<div id="photos">
  <% if @photos %>
    <ul>
    <% @photos.each do |photo| %>
      <li>
        <%= image_tag photo.file.url %><br />
        <% if photo.metadata['photo']['tags'] %>
          <% tag_names = [] %>
          <% photo.metadata['photo']['tags']['data'].each do |tag| %>
            <% if tag['id'] && photo.service.uid == tag['id'] %>
            <% elsif tag['id'] %>
              <% tag_names << link_to(tag['name'], 
                                      chat_path(:provider => photo.service.provider.name,
                                                :uid => tag['id'],
                                                :name => tag['name']) ) %>
            <% else %>
              <% tag_names << h(tag['name']) %>
            <% end %>
          <% end %>
          <%=raw tag_names.join(', ') %>
        <% end %>
      </li>
    <% end %>
    </ul>
  <% else %>
    There are no photos yet
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookImagesUpload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/services/_import_message.html.erb
<% if service.import_ended_at %>
  <%=t ".#{service.provider.name}_import_ended", :count => service.import_total_photos %>
  <% if service.import_total_photos != 0 %>
    <%= link_to t('.go_to_uncategorized'), current_user.events.first %>.
  <% end %>
<% elsif service.import_total_photos and service.import_num_photos %>
  <%=t ".#{service.provider.name}_import_running", :num_photos => service.import_num_photos, :total_photos => service.import_total_photos %>
<% elsif !service.import_total_photos %>
  <%=t ".#{service.provider.name}_import_started" %>
<% end %>

app/views/services/_import_statuses.html.erb
<% current_user.services.each do |service| %>
  <% if service.import_started_at %>
    <div id="service_<%= service.id %>_import_status" class="notice">
      <%= render :partial => 'services/import_message', :locals => {:service => service} %>
    </div>
    <script>
      setTimeout(function() {update_import_status(<%= service.id %>);}, 3000);
    </script>
  <% end %>
<% end %>

app/views/services/_list.html.erb
<% unauthorized_providers = [] %>
<% authorized_services = [] %>
<% Provider.order('"order"').all.each do |p| %>
  <% s = current_user.services.find_by_provider_id(p.id) %>
  <% s ? authorized_services << s : unauthorized_providers << p %>
<% end %>

<div id="services">
<% if authorized_services.size > 0 %>
  <h2><%=t '.services' %></h2>
  <ul>
  <% authorized_services.each do |s| %>
      <li>
        [<%= link_to 'x', s, :confirm => t('.confirm_remove_service'), :method => :delete %>]
        <%= link_to t(".#{s.provider.name}"), import_path(s.provider.name) %>
      </li>
  <% end %>
  </ul>
<% end %>
<% if unauthorized_providers.size > 0 %>
  <h2><%=t '.add_service' %></h2>
  <ul>
  <% unauthorized_providers.each do |p| %>
    <li><%= link_to t(".#{p.name}"), "/auth/#{p.name}" %></li>
  <% end %>
  </ul>
<% end %>
</div>

app/views/services/create_invitation.html.erb
<h2>Invitation posted on <%= params[:name] %>'s wall</h2>
<%# TODO: change copy %>
<%= link_to "Go back to events", events_path(1) %>

app/views/services/import_status.js.erb
$('#service_<%= @service.id %>_import_status').html('<%=escape_javascript(render(:partial => "services/import_message", :locals => {:service=>@service})) %>');
<% if @service.import_ended_at %>
  setTimeout(function() {$('#service_<%= @service.id %>_import_status').fadeOut();}, 30000)
  <% @service.update_attributes( 
      :import_started_at => nil,
      :import_ended_at => nil,
      :import_num_photos => nil,
      :import_total_photos => nil ) %>
<% else %>
  setTimeout(function() {update_import_status(<%= @service.id %>);}, 3000);
<% end %>

app/views/services/invite.html.erb
<%# TODO: change copy %>
<h2>Post an invitation on <%= params[:name] %>'s wall:</h2>
<%= form_tag( service_create_invitation_path(:provider => params[:provider], :uid => params[:uid], :name => params[:name]), :method=>:post ) do %>
  <p><%= text_area_tag :message, (params[:message] || "I'd like to invite you to Pixelmate!") %></p>
  <p><%= submit_tag 'Submit' %></p>
<% end %>